const botdata = {
    "hello": "Hello! How can I assist you?",
    "hi": "Hello! How can I assist you?",
    "how are you": "I'm doing great, thanks for asking!",
    "name": "I am a friendly chatbot!",
    "bye": "Goodbye! Have a nice day!",
    "pet care": "Taking care of your pet involves regular vet check-ups, a balanced diet, daily exercise, and proper grooming.",
    "dog diet": "A balanced diet for dogs typically includes high-quality dog food with proteins, fats, carbohydrates, and essential vitamins.",
    "vet visit": "Cats should be taken to the vet at least once a year for a general check-up, vaccinations, and preventive care.",
    "healthy pet": "Healthy pets typically have shiny coats, clear eyes, healthy gums, and normal energy levels.",
    "exercise routine": "Exercise is essential for pets' health. For dogs, daily walks and playtime are great. Cats benefit from interactive toys and climbing structures.",
    "anxiety": "If your pet is anxious, try providing a quiet and comfortable space, avoid loud noises, and use calming aids like pheromone diffusers or toys.",
    "dog grooming": "Regular grooming for dogs includes brushing their coat, trimming nails, cleaning ears, and maintaining oral hygiene. For more information check out the grooming section.",
    "cat grooming": "Cats are generally good at grooming themselves, but regular brushing and nail trimming are still important. For more information check ou the grooming section.",
    "puppy care": "Puppy care includes providing a balanced diet, regular vet visits, socialization, crate training, and plenty of exercise. For more information check out the services available.",
    "kitten care": "Kitten care involves ensuring they receive the proper vaccinations, a balanced diet, and early socialization with humans and other pets. For more information check out the services available.",
    "dog training": "Dog training involves teaching basic commands, potty training, and socializing your dog to be comfortable with other pets and people. For more information check out the services available.",
    "cat training": "Cat training can include teaching basic commands like 'sit' or 'come', litter box training, and discouraging unwanted behaviors. For more information check out the services available.",
    "pet vaccinations": "Pets should receive core vaccinations based on their species and age. Common vaccinations include rabies, distemper, and parvovirus for dogs.",
    "dog diseases": "Common dog diseases include parvovirus, kennel cough, and heartworm. Regular vet check-ups can help detect and prevent many of these diseases.",
    "cat diseases": "Common cat diseases include feline leukemia, feline immunodeficiency virus, and upper respiratory infections. Regular vet visits are essential.",
    "pet insurance": "Pet insurance can help cover the cost of veterinary care, medications, and surgeries. It's a great way to protect your pet's health financially.",
    "dog breeds": "There are many dog breeds, ranging from small ones like Chihuahuas to large breeds like Great Danes. Each breed has specific care requirements.",
    "cat breeds": "Cat breeds like Persian, Siamese, and Maine Coon have unique grooming, health, and temperament needs.",
    "pet adoption": "Adopting a pet is a rewarding experience! Be sure to research the pet's needs, lifestyle compatibility, and commit to their lifelong care.",
    "spaying and neutering": "Spaying and neutering help prevent unwanted pregnancies, reduce pet overpopulation, and can improve your pet's health and behavior.",
    "dog walking": "Walking your dog daily is essential for their physical and mental health. Ensure they are on a leash and allow them to explore safely.",
    "cat scratching": "Cats have a natural instinct to scratch. Provide scratching posts, pads, and other appropriate outlets to satisfy this behavior.",
    "pet allergies": "Pet allergies are common, both in humans and pets. If you suspect allergies, visit a vet for a proper diagnosis and management options.",
    "dog separation anxiety": "If your dog experiences separation anxiety, try crate training, giving them toys, and gradually increasing the time they spend alone.",
    "cat litter box": "A clean and appropriately-sized litter box is essential for your cat. Be sure to scoop it daily and change the litter regularly.",
     "pet health checkup": "Regular vet visits are important for monitoring your pet's overall health, getting vaccinations, and preventing common illnesses.",
    "pet weight management": "Keep track of your pet's weight. Regular exercise and portion-controlled meals are key to managing your pet's weight and preventing obesity.",
    "flea treatment": "Fleas are common parasites. Use flea treatments recommended by your vet, such as topical treatments, collars, or oral medications.",
    "tick prevention": "Ticks can transmit diseases. Use tick prevention treatments and regularly check your pet after outdoor activities, especially in wooded areas.",
    "pet dental care": "Brush your pet's teeth regularly and provide dental chews to prevent plaque buildup and promote healthy gums and teeth.",
    "pet hydration": "Ensure your pet always has access to clean, fresh water to stay hydrated, especially during hot weather or after exercise.",
    "dog breeds for apartment": "Some dog breeds like French Bulldogs, Cavalier King Charles Spaniels, and Dachshunds do well in apartments because of their small size and low exercise needs.",
    "cat breeds for apartment": "Cat breeds like Scottish Folds, Ragdolls, and British Shorthairs are generally well-suited for apartment living due to their calm nature."
  };
  
  export default botdata;