export const dogBreedInfo = {
    bulldog: {
      name: 'Bulldog',
      description: 'Bulldogs are muscular, heavyset dogs known for their lovable and gentle personalities.',
      temperament: 'Gentle, Courageous, Friendly',
      size: 'Medium',
      origin: 'England',
    },
    poodle: {
      name: 'Poodle',
      description: 'Poodles are elegant dogs with curly coats. They are very intelligent and hypoallergenic.',
      temperament: 'Active, Proud, Intelligent',
      size: 'Medium',
      origin: 'Germany/France',
    },
    beagle: {
      name: 'Beagle',
      description: 'Beagles are friendly and curious dogs that have an excellent sense of smell.',
      temperament: 'Curious, Merry, Friendly',
      size: 'Small',
      origin: 'England',
    },
    maltese: {
      name: 'Maltese',
      description: 'Maltese are small, fluffy dogs that are known for their affectionate nature and long, silky white coat.',
      temperament: 'Affectionate, Playful, Gentle',
      size: 'Small',
      origin: 'Malta',
    },
    pug: {
      name: 'Pug',
      description: 'Pugs are small, sturdy dogs with charming, wrinkled faces. They are known for their affectionate and playful nature.',
      temperament: 'Playful, Affectionate, Sociable, Loyal, Friendly, Stubborn',
      size: 'Small',
      origin: 'China',
    },
    chihuahua: {
      name: 'Chihuahua',
      description: 'Chihuahuas are the smallest dog breed known for their big personalities and loyalty.',
      temperament: 'Loyal, Brave, Active',
      size: 'Small',
      origin: 'Mexico',
    },
  
    collie: {
      name: 'Collie',
      description: 'Collies are herding dogs known for their intelligence, loyalty, and distinctive long coat.',
      temperament: 'Gentle, Intelligent, Loyal',
      size: 'Large',
      origin: 'Scotland',
    },
    labrador: {
      name: 'Labrador Retriever',
      description: 'Labradors are friendly, intelligent, and energetic dogs that are highly trainable.',
      temperament: 'Friendly, Intelligent, Active',
      size: 'Large',
      origin: 'Canada',
    },
    retriever: {
      name: 'Retriever',
      description: 'Retrievers are known for being highly trainable and are great for active families.',
      temperament: 'Friendly, Intelligent, Energetic',
      size: 'Large',
      origin: 'United Kingdom',
    },
    germanshepherd: {
      name: 'German Shepherd',
      description: 'German Shepherds are courageous, confident, and highly trainable dogs known for their intelligence and versatility.',
      temperament: 'Courageous, Intelligent, Loyal',
      size: 'Large',
      origin: 'Germany',
    },
    spaniel: {
      name: 'Spaniel',
      description: 'Spaniels are friendly and affectionate dogs, often used for hunting and as companions.',
      temperament: 'Loyal, Friendly, Energetic',
      size: 'Medium',
      origin: 'United Kingdom',
    },
    setter: {
      name: 'Setter',
      description: 'Setters are active, intelligent dogs, originally bred for bird hunting.',
      temperament: 'Energetic, Friendly, Active',
      size: 'Medium',
      origin: 'United Kingdom',
    },
  
    rottweiler: {
      name: 'Rottweiler',
      description: 'Rottweilers are large, powerful dogs known for their loyalty, protectiveness, and confidence.',
      temperament: 'Loyal, Confident, Protective',
      size: 'Large',
      origin: 'Germany',
    },
    doberman: {
      name: 'Doberman',
      description: 'Dobermans are intelligent, alert, and strong dogs known for their loyalty and protective nature.',
      temperament: 'Loyal, Alert, Intelligent',
      size: 'Large',
      origin: 'Germany',
    },
    boxer: {
      name: 'Boxer',
      description: 'Boxers are playful, energetic dogs with a strong and muscular build, known for their affection and loyalty.',
      temperament: 'Playful, Energetic, Loyal',
      size: 'Medium',
      origin: 'Germany',
    },
    malinois: {
      name: 'Malinois',
      description: 'Belgian Malinois are strong, hardworking dogs often used in police and military work due to their intelligence and agility.',
      temperament: 'Intelligent, Active, Loyal',
      size: 'Medium',
      origin: 'Belgium',
    },
    akita: {
      name: 'Akita',
      description: 'Akitas are large, powerful dogs originally bred for guarding. They are loyal and protective of their families.',
      temperament: 'Loyal, Protective, Brave',
      size: 'Large',
      origin: 'Japan',
    },
    mastiff: {
      name: 'Mastiff',
      description: 'Mastiffs are giant dogs known for their protective nature and calm demeanor.',
      temperament: 'Calm, Protective, Loyal',
      size: 'Giant',
      origin: 'England',
    },
  
    husky: {
      name: 'Husky',
      description: 'Siberian Huskies are known for their striking blue eyes and thick double coat. They are energetic and hardworking.',
      temperament: 'Energetic, Friendly, Independent',
      size: 'Medium',
      origin: 'Siberia',
    },
    malamute: {
      name: 'Malamute',
      description: 'Alaskan Malamutes are large, strong, and powerful dogs originally bred to haul heavy freight.',
      temperament: 'Strong, Independent, Loyal',
      size: 'Large',
      origin: 'Alaska',
    },
    dane: {
      name: 'Great Dane',
      description: 'Great Danes are enormous dogs known for their gentle nature, making them excellent companions.',
      temperament: 'Gentle, Friendly, Loyal',
      size: 'Giant',
      origin: 'Germany',
    },
    samoyed: {
      name: 'Samoyed',
      description: 'Samoyeds are fluffy, white dogs known for their happy disposition and gentle nature.',
      temperament: 'Friendly, Affectionate, Playful',
      size: 'Medium',
      origin: 'Siberia',
    },
  
    pomeranian: {
      name: 'Pomeranian',
      description: 'Pomeranians are small, lively dogs with a fluffy coat and a friendly demeanor.',
      temperament: 'Friendly, Lively, Outgoing',
      size: 'Small',
      origin: 'Germany/Poland',
    },
    papillon: {
      name: 'Papillon',
      description: 'Papillons are small, intelligent dogs with large ears. They are friendly and great with families.',
      temperament: 'Intelligent, Friendly, Active',
      size: 'Small',
      origin: 'France',
    },
  };
  
  
  // catBreedInfo Data containing information for all breeds
export const catBreedInfo = {
    persian: {
      name: 'Persian',
      description: 'Persian cats are known for their long, luxurious coats and calm, affectionate personalities.',
      temperament: 'Gentle, Affectionate, Quiet',
      size: 'Medium',
      origin: 'Iran',
    },
    bengal: {
      name: 'Bengal',
      description: 'Bengal cats have a wild appearance, with a leopard-like coat pattern. They are active, playful, and intelligent.',
      temperament: 'Active, Intelligent, Playful',
      size: 'Medium',
      origin: 'United States',
    },
    ragdoll: {
      name: 'Ragdoll',
      description: 'Ragdolls are large, gentle, and affectionate cats. They often go limp when picked up, hence the name "Ragdoll."',
      temperament: 'Affectionate, Gentle, Relaxed',
      size: 'Large',
      origin: 'United States',
    },
    siamese: {
      name: 'Siamese',
      description: 'Siamese cats are known for their striking blue eyes, short coat, and outgoing personality.',
      temperament: 'Vocal, Intelligent, Sociable',
      size: 'Medium',
      origin: 'Thailand',
    },
    burmese: {
      name: 'Burmese',
      description: 'Burmese cats are small to medium-sized, with a playful, affectionate personality and a sleek, shiny coat.',
      temperament: 'Affectionate, Playful, Vocal',
      size: 'Medium',
      origin: 'Burma (Myanmar)',
    },
    sphynx: {
      name: 'Sphynx',
      description: 'The Sphynx is a hairless breed, known for its wrinkled skin and friendly, outgoing nature.',
      temperament: 'Affectionate, Energetic, Social',
      size: 'Medium',
      origin: 'Canada',
    },
  
    van: {
      name: 'Van',
      description: 'Turkish Van cats are known for their love of water and distinctive color patterns. They are playful and independent.',
      temperament: 'Playful, Energetic, Independent',
      size: 'Medium',
      origin: 'Turkey',
    },
    savannah: {
      name: 'Savannah',
      description: 'Savannah cats are exotic-looking, with a wild appearance. They are intelligent, playful, and active.',
      temperament: 'Active, Intelligent, Social',
      size: 'Large',
      origin: 'United States',
    },
    abyssinian: {
      name: 'Abyssinian',
      description: 'Abyssinians are agile, active, and curious cats. They have a short, ticked coat and are often considered one of the oldest domestic cat breeds.',
      temperament: 'Active, Playful, Intelligent',
      size: 'Medium',
      origin: 'Ethiopia',
    },
    shorthair: {
      name: 'Shorthair',
      description: 'Shorthair cats are known for their calm demeanor and affectionate nature. They come in a variety of colors and patterns.',
      temperament: 'Affectionate, Calm, Independent',
      size: 'Medium',
      origin: 'Various (UK, US)',
    },
  
    siberian: {
      name: 'Siberian',
      description: 'Siberians are large, strong, and fluffy cats with a playful, affectionate nature. They are known for their love of water.',
      temperament: 'Playful, Affectionate, Intelligent',
      size: 'Large',
      origin: 'Russia',
    },
    fold: {
      name: 'Scottish Fold',
      description: 'Scottish Folds are easily recognized by their unique folded ears. They are calm, affectionate, and great companions.',
      temperament: 'Affectionate, Calm, Loyal',
      size: 'Medium',
      origin: 'Scotland',
    },
    mainecoon: {
      name: 'Maine Coon',
      description: 'Maine Coons are large, friendly, and playful cats, known for their tufted ears and long, thick fur.',
      temperament: 'Friendly, Playful, Sociable',
      size: 'Large',
      origin: 'United States',
    },
  
    egyptianmau: {
      name: 'Egyptian Mau',
      description: 'Egyptian Mau cats are known for their exotic appearance, with spotted coats and bright green eyes. They are intelligent and active.',
      temperament: 'Active, Intelligent, Affectionate',
      size: 'Medium',
      origin: 'Egypt',
    },
    manx: {
      name: 'Manx',
      description: 'Manx cats are unique for their short or absent tails. They are calm, intelligent, and good family companions.',
      temperament: 'Calm, Intelligent, Playful',
      size: 'Medium',
      origin: 'Isle of Man',
    },
    angora: {
      name: 'Angora',
      description: 'Angora cats have a long, silky coat and are known for being playful and affectionate.',
      temperament: 'Playful, Affectionate, Active',
      size: 'Medium',
      origin: 'Turkey',
    },
  };